sudo: false

language: php

php:
  - '7.1'
  - '7.2'
  - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

stages:
    - lint
    - test

before_script:
    - composer install

jobs:
    - stage: lint
      script: composer lint
    - stage: test
      script: composer test

